export const categories: { id: number; name: string }[] = [
  { id: 1, name: "Developer" },
  { id: 2, name: "Dermatologist" },
  { id: 3, name: "Massage" },
  { id: 4, name: "Personal Trainer" },
  { id: 5, name: "Nutritionist" },
  { id: 6, name: "Graphic Designer" },
  { id: 7, name: "Photographer" },
  { id: 8, name: "Videographer" },
  { id: 9, name: "Electrician" },
  { id: 10, name: "Plumber" },
  { id: 11, name: "Carpenter" },
  { id: 12, name: "Mechanic" },
  { id: 13, name: "Tutor" },
  { id: 14, name: "Music Teacher" },
  { id: 15, name: "Yoga Instructor" },
  { id: 16, name: "Hair Stylist" },
  { id: 17, name: "Makeup Artist" },
  { id: 18, name: "Painter" },
  { id: 19, name: "Interior Designer" },
  { id: 20, name: "Architect" },
  { id: 21, name: "Web Designer" },
  { id: 22, name: "UI/UX Designer" },
  { id: 23, name: "App Developer" },
  { id: 24, name: "Software Engineer" },
  { id: 25, name: "Copywriter" },
  { id: 26, name: "Content Writer" },
  { id: 27, name: "SEO Specialist" },
  { id: 28, name: "Digital Marketer" },
  { id: 29, name: "Social Media Manager" },
  { id: 30, name: "Translator" },
  { id: 31, name: "Voice Actor" },
  { id: 32, name: "Event Planner" },
  { id: 33, name: "Wedding Planner" },
  { id: 34, name: "Fitness Coach" },
  { id: 35, name: "Life Coach" },
  { id: 36, name: "Therapist" },
  { id: 37, name: "Psychologist" },
  { id: 38, name: "Chiropractor" },
  { id: 39, name: "Doctor" },
  { id: 40, name: "Nurse" },
  { id: 41, name: "Dentist" },
  { id: 42, name: "Veterinarian" },
  { id: 43, name: "Dog Walker" },
  { id: 44, name: "Pet Groomer" },
  { id: 45, name: "House Cleaner" },
  { id: 46, name: "Gardener" },
  { id: 47, name: "Chef" },
  { id: 48, name: "Baker" },
  { id: 49, name: "Barber" },
  { id: 50, name: "Tattoo Artist" },
  { id: 51, name: "Tailor" },
  { id: 52, name: "Fashion Designer" },
  { id: 53, name: "Real Estate Agent" },
  { id: 54, name: "Financial Advisor" },
  { id: 55, name: "Tax Consultant" },
  { id: 56, name: "Lawyer" },
  { id: 57, name: "Paralegal" },
  { id: 58, name: "Notary Public" },
  { id: 59, name: "IT Support Specialist" },
  { id: 60, name: "Network Engineer" },
  { id: 61, name: "Cybersecurity Analyst" },
  { id: 62, name: "Data Scientist" },
  { id: 63, name: "Machine Learning Engineer" },
  { id: 64, name: "Blockchain Developer" },
  { id: 65, name: "AI Researcher" },
  { id: 66, name: "Game Developer" },
  { id: 67, name: "3D Artist" },
  { id: 68, name: "Animator" },
  { id: 69, name: "Video Editor" },
  { id: 70, name: "Sound Engineer" },
  { id: 71, name: "DJ" },
  { id: 72, name: "Musician" },
  { id: 73, name: "Singer" },
  { id: 74, name: "Actor" },
  { id: 75, name: "Model" },
  { id: 76, name: "Caterer" },
  { id: 77, name: "Waiter" },
  { id: 78, name: "Bartender" },
  { id: 79, name: "Security Guard" },
  { id: 80, name: "Construction Worker" },
  { id: 81, name: "Welder" },
  { id: 82, name: "Truck Driver" },
  { id: 83, name: "Delivery Driver" },
  { id: 84, name: "Mechanic Engineer" },
  { id: 85, name: "Civil Engineer" },
  { id: 86, name: "Electrical Engineer" },
  { id: 87, name: "Chemical Engineer" },
  { id: 88, name: "Biomedical Engineer" },
  { id: 89, name: "Teacher" },
  { id: 90, name: "Professor" },
  { id: 91, name: "Librarian" },
  { id: 92, name: "Accountant" },
  { id: 93, name: "Banker" },
  { id: 94, name: "Insurance Agent" },
  { id: 95, name: "Pharmacist" },
  { id: 96, name: "Lab Technician" },
  { id: 97, name: "Researcher" },
  { id: 98, name: "HR Consultant" },
  { id: 99, name: "Recruiter" },
  { id: 100, name: "Project Manager" },
  { id: 101, name: "Product Manager" },
  { id: 102, name: "Operations Manager" },
  { id: 103, name: "Sales Representative" },
  { id: 104, name: "Customer Support Agent" },
  { id: 105, name: "Other(Write to description)" },
];
