export const categories: Array<string> = [
  "Developer",
  "Dermatologist",
  "Massage",
  "Personal Trainer",
  "Nutritionist",
  "Graphic Designer",
  "Photographer",
  "Videographer",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Mechanic",
  "Tutor",
  "Music Teacher",
  "Yoga Instructor",
  "Hair Stylist",
  "Makeup Artist",
  "Painter",
  "Interior Designer",
  "Architect",
  "Web Designer",
  "UI/UX Designer",
  "App Developer",
  "Software Engineer",
  "Copywriter",
  "Content Writer",
  "SEO Specialist",
  "Digital Marketer",
  "Social Media Manager",
  "Translator",
  "Voice Actor",
  "Event Planner",
  "Wedding Planner",
  "Fitness Coach",
  "Life Coach",
  "Therapist",
  "Psychologist",
  "Chiropractor",
  "Doctor",
  "Nurse",
  "Dentist",
  "Veterinarian",
  "Dog Walker",
  "Pet Groomer",
  "House Cleaner",
  "Gardener",
  "Chef",
  "Baker",
  "Barber",
  "Tattoo Artist",
  "Tailor",
  "Fashion Designer",
  "Real Estate Agent",
  "Financial Advisor",
  "Tax Consultant",
  "Lawyer",
  "Paralegal",
  "Notary Public",
  "IT Support Specialist",
  "Network Engineer",
  "Cybersecurity Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "Blockchain Developer",
  "AI Researcher",
  "Game Developer",
  "3D Artist",
  "Animator",
  "Video Editor",
  "Sound Engineer",
  "DJ",
  "Musician",
  "Singer",
  "Actor",
  "Model",
  "Caterer",
  "Waiter",
  "Bartender",
  "Security Guard",
  "Construction Worker",
  "Welder",
  "Truck Driver",
  "Delivery Driver",
  "Mechanic Engineer",
  "Civil Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Biomedical Engineer",
  "Teacher",
  "Professor",
  "Librarian",
  "Accountant",
  "Banker",
  "Insurance Agent",
  "Pharmacist",
  "Lab Technician",
  "Researcher",
  "HR Consultant",
  "Recruiter",
  "Project Manager",
  "Product Manager",
  "Operations Manager",
  "Sales Representative",
  "Customer Support Agent",
];